name: Package and upload addon

on:
  workflow_dispatch:
  push:
    branches:
      - master
      - main
    tags:
      - '*'
    paths-ignore:
      - '.github/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Package
        uses: BigWigsMods/packager@v2.0.3
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          GITHUB_OAUTH: ${{ secrets.GITHUB_TOKEN }}
